---
- hosts: all
  become: yes
  
  # Define user and password variables
  vars:
        username: peter   
        passwords: Scania2007
        grupp: admin
  
  tasks:
      - name: Ensure that "core" application is installed
        yum: 
          name: "{{ item }}"
          state: present 
        with_items:
          - tree
          - git
          - sshpass
          - openssl-devel

      # Define task to add group
      - name: Check that groups "{{ grupp }}" is present. Create if needed
        group: 
          name: "{{ grupp }}" 
          state: present

      # Define task to add user    
      - name: Check that user bork is present. Create if needed
        user: 
          name: "{{ username }}" 
          shell: /bin/bash 
          home: /home/bork 
          groups: "{{ grupp }}" 
          generate_ssh_key: yes 
          ssh_key_bits: 2048 
          password: "{{ passwords }}" 
        
...