---
- hosts: all
  become: yes

  vars:
      username: docker
      groupname: admin
      pw: $6$tLEwslYoG1ZIPAGN$EZy1YxQLJuLYJhX7k5iG9ZbBYvyT6f9V9xBMuXgtGDrUpNSUl3FV8uDOtY4aAHCbNisMKwsvnRWaYnJp.9Qj//

  tasks:
      - name: Ensure that "core" application is installed
        yum: name={{item}} state=present
        with_items:
          - tree
          - git
          - sshpass
          - openssl-devel
          - python-pip
      

      - name: Install global python requirements
        pip: name={{item}} state=present
        with_items:
          - docker-compose

      - name: Check that group admin is present. Create if needed
        group: 
          name: "{{ groupname }}"
          state: present

      - name: Create new user
        user: 
          name: "{{ username }}"
          shell: /bin/bash 
          home: "/home/{{ username }}"
          groups: "{{ groupname }}" 
          generate_ssh_key: yes 
          ssh_key_bits: 2048 
          password:   "{{ pw }}"

      - name: Copy files 
        copy: 
          src: data/
          dest: "/home/{{ username }}/data/"
          owner: "{{ username }}" 
          group: "{{ username }}" 
          mode: 0644 

      # Download Docker install script
      - name: download get.docker script to tmp dir
        get_url: 
          url: https://get.docker.com/
          dest: /tmp/get-docker.sh
          mode: 0755

      # Download and install latest Docker 
      - name: Download and install latest Docker 
        shell: /tmp/get-docker.sh

      # Start Docker 
      - name: Start docker service
        shell: systemctl start docker
        



...